# Generated by Django 4.1.3 on 2022-12-14 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Noname', max_length=50, unique=True)),
                ('short_name', models.CharField(default='N/A', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100, unique=True)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='creation date')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='creation date')),
                ('last_updated', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='creation date')),
                ('gender', models.CharField(choices=[('MALE', '男性'), ('FEMALE', '女性'), ('UNISEX', '男/女')], default='UNISEX', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('stock_quantity', models.BigIntegerField(default=0)),
                ('reference_price', models.FloatField(default=0.0)),
                ('retail_price', models.FloatField(default=0.0)),
                ('resell_price', models.FloatField(default=0.0)),
                ('tax_percentage', models.FloatField(default=0)),
                ('promotion_profit_percentage', models.FloatField(default=0.0)),
                ('regular_profit_percentage', models.FloatField(default=0.0)),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_of_brand', to='shop.brand')),
                ('category', models.ManyToManyField(related_name='related_products', to='shop.category')),
                ('image_list', models.ManyToManyField(related_name='related_products', to='shop.image')),
                ('retailer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_of_retailer', to='shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('barcode', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_tags', to='shop.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_tags', to='shop.product')),
                ('size_list', models.ManyToManyField(to='shop.size')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField(default=0)),
                ('additional_discount_percentage', models.FloatField(default=0)),
                ('pre_discount_amount_off', models.FloatField(default=0)),
                ('post_discount_amount_off', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='creation date')),
                ('expire_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_promotions', to='shop.product')),
            ],
        ),
    ]
