# Generated by Django 4.1.4 on 2022-12-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_image_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='token',
            new_name='uuid',
        ),
    ]
