# Generated by Django 4.1.4 on 2022-12-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_token_image_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='s3_key',
            field=models.CharField(default=213213, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
