# Generated by Django 4.1.4 on 2022-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_category_list_alter_product_image_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_list',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_list',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='shop.image'),
        ),
    ]
