# Generated by Django 4.1.4 on 2022-12-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_category_list_alter_product_image_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='cn_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
